// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/projects");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"RA-DAR\"]");
// ---record---
await subtitleSpan("분석 담당자가 소스 디렉터리 하나로 하루 일을 끝내는 흐름입니다", HOLD[0], async () => {
  await highlight("role=heading[name=\"RA-DAR\"]", {});
}, {"emphasis": "소스 디렉터리 하나로"});
await subtitleSpan("먼저 새 프로젝트를 등록하고 분석을 걸어 둡니다", HOLD[1], null, {"emphasis": "걸어 둡니다"});
await padTo(DWELL);
