// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/scenarios");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"사용자 시나리오 9건\"]");
// ---record---
await subtitleSpan("분석이 끝난 프로젝트에서 업무 분류별 시나리오를 읽습니다", HOLD[0], async () => {
  await highlight(".sheet-gp >> nth=0", {});
}, {"emphasis": "업무 분류별"});
await padTo(DWELL);
