// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/executions/EXE-20260908-0042");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 수행\"]");
// ---record---
await subtitleSpan("도출된 케이스를 실제 화면에 수행시켜 판정을 받습니다", HOLD[0], async () => {
  await highlight("role=heading[name=\"수행 대기열\"]", {});
}, {"emphasis": "실제 화면"});
await padTo(DWELL);
