// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/evidence/EXE-20260908-0042/EVD-0042-SCN-LEDGER-001-2");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"실패 증적 상세\"]");
// ---record---
await subtitleSpan("판정 근거는 증적에서 프레임과 좌표로 확인합니다", HOLD[0], async () => {
  await highlight("role=heading[name=\"대상 화면 캡처\"]", {});
}, {"emphasis": "프레임과 좌표"});
await padTo(DWELL);
