// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/evidence/EXE-20260908-0042/EVD-0042-SCN-LEDGER-001-2");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"실패 증적 상세\"]");
// ---record---
await subtitleSpan("화면마다 어떤 모델 동작이 그 결과를 만들었는지 함께 설명합니다", HOLD[0], null, {"emphasis": "모델 동작"});
await padTo(DWELL);
