// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=progress#/workspace");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"WIKI 단계 수행 중\"]");
// ---record---
await subtitleSpan("분석 중인 프로젝트를 열면 진행률과 수행 중인 단계가 보입니다", HOLD[0], async () => {
  await highlight("role=progressbar", {});
}, {"emphasis": "진행률"});
await padTo(DWELL);
