// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=progress#/workspace");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"WIKI 단계 수행 중\"]");
// ---record---
await subtitleSpan("소스 스캔, 사실 추출, 업무 분류를 거쳐 시나리오를 씁니다", HOLD[0], null, {"emphasis": "업무 분류"});
await subtitleSpan("세부 단계는 열 개이고 완료된 것부터 체크됩니다", HOLD[1], async () => {
  await highlight("role=list[name=\"세부 생성 단계\"]", {});
}, {"emphasis": "열 개"});
await padTo(DWELL);
