// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=progress#/workspace");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"WIKI 단계 수행 중\"]");
// ---record---
await subtitleSpan("전체 분석은 약 70분이 걸리므로 걸어 두고 다른 일을 하세요", HOLD[0], null, {"emphasis": "약 70분"});
await subtitleSpan("진행 중에도 다른 프로젝트의 이력과 증적은 그대로 봅니다", HOLD[1], null, {"emphasis": "그대로"});
await padTo(DWELL);
