// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=progress#/workspace");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"WIKI 단계 수행 중\"]");
// ---record---
await subtitleSpan("끝나면 생성 이력에 회차로 쌓이고 목록에서 다시 열 수 있습니다", HOLD[0], async () => {
  await hoverOn("role=button[name=\"다른 프로젝트 선택\"]");
}, {"emphasis": "생성 이력"});
await padTo(DWELL);
