// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/projects");
await page.waitForLoadState('networkidle');
await waitFor("role=button[name=\"열기\"]");
// ---record---
await subtitleSpan("분석이 끝난 프로젝트는 열기로 바로 시나리오 케이스가 열립니다", HOLD[0], async () => {
  await click("role=button[name=\"열기\"]");
  await waitFor("role=heading[name=\"사용자 시나리오 9건\"]", {});
}, {"emphasis": "바로"});
await padTo(DWELL);
