// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto(BASE + "/?preview=demo#/workspace");
await page.waitForLoadState('networkidle');
await waitFor("role=tab[name=/생성 이력/]");
// ---record---
await subtitleSpan("개요에서 생성 이력, 테스트 실행, 증적 수를 한눈에 봅니다", HOLD[0], async () => {
  await click("role=tab[name=/생성 이력/]");
  await waitFor("role=heading[name=\"생성 이력\"]", {});
}, {"emphasis": "한눈에"});
await padTo(DWELL);
