// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/scenarios");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"사용자 시나리오 9건\"]");
// ---record---
await subtitleSpan("생성 이력 탭에는 분석 회차가 쌓입니다", HOLD[0], async () => {
  await click("role=tab[name=/생성 이력/]");
  await waitFor("role=heading[name=\"생성 이력\"]", {});
}, {"emphasis": "분석 회차"});
await padTo(DWELL);
