// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto(BASE + "/?preview=demo#/runs");
await page.waitForLoadState('networkidle');
await waitFor("role=button[name=/RUN-preview-02/]");
// ---record---
await subtitleSpan("회차를 열면 그때 도출된 시나리오가 그대로 열립니다", HOLD[0], async () => {
  await click("role=button[name=/RUN-preview-02/]");
  await waitFor("role=heading[name=\"사용자 시나리오 9건\"]", {});
}, {"emphasis": "회차"});
await padTo(DWELL);
