// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/scenarios");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"사용자 시나리오 9건\"]");
// ---record---
await subtitleSpan("시나리오는 업무 분류별 시트로 정리됩니다", HOLD[0], async () => {
  await highlight(".sheet-gp >> nth=0", {});
}, {"emphasis": "업무 분류별"});
await subtitleSpan("행마다 ID, 목적, 원천 파일, 단계 수가 있습니다", HOLD[1], null, {"emphasis": "원천 파일"});
await padTo(DWELL);
