// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/scenarios");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"사용자 시나리오 9건\"]");
// ---record---
await subtitleSpan("이 시트는 네 단계 모델 작업의 결과입니다", HOLD[0], async () => {
  await zoom(".sheet-gp >> nth=0", {"scale": 1.3});
}, {"emphasis": "네 단계"});
await subtitleSpan("SRC와 FACT가 소스 사실을 모으고 WIKI와 SCENARIO가 씁니다", HOLD[1], async () => {
  await zoomOut();
}, {"emphasis": "WIKI와 SCENARIO"});
await padTo(DWELL);
