// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/scenarios");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"사용자 시나리오 9건\"]");
// ---record---
await subtitleSpan("케이스를 펼치면 단계와 기대 결과가 함께 보입니다", HOLD[0], async () => {
  await zoom(".sheet-rw >> nth=2", {"scale": 1.3});
  await click("role=button[name=\"3 steps\"] >> nth=1");
  await zoomOut();
}, {"emphasis": "기대 결과"});
await padTo(DWELL);
