// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/scenarios");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"사용자 시나리오 9건\"]");
// ---record---
await subtitleSpan("시트를 내려도 질의 패널과 자막은 그 자리에 있습니다", HOLD[0], async () => {
  await scrollTo(".panel-s", {"toRatio": 1});
}, {"emphasis": "그 자리"});
await padTo(DWELL);
