// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/scenarios");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"사용자 시나리오 9건\"]");
// ---record---
await subtitleSpan("케이스를 질의 패널로 끌어 놓으면 참조로 잡힙니다", HOLD[0], async () => {
  await drag(".sheet-rw >> nth=0", ".comp .drop", {"mode": "html5"});
  await waitFor("[aria-label=\"참조할 시나리오\"]", {});
  await zoom("[aria-label=\"참조할 시나리오\"]", {"scale": 1.4});
  await highlight("[aria-label=\"참조할 시나리오\"]", {});
  await zoomOut();
}, {"emphasis": "끌어 놓으면"});
await padTo(DWELL);
