// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/scenarios");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"사용자 시나리오 9건\"]");
// ---record---
await subtitleSpan("질문하면 케이스의 전제와 단계를 기준으로 답합니다", HOLD[0], async () => {
  await drag(".sheet-rw >> nth=0", ".comp .drop", {"mode": "html5"});
  await typeText("role=textbox[name=\"시나리오 질문\"]", "실패할 수 있는 분기는 무엇인가요?", { secret: false });
  await click("role=button[name=\"보내기\"]");
  await zoom(".chat-s", {"scale": 1.4});
  await waitStream(".chat-s .msg >> nth=-1", {"until": "stable", "stableMs": 1200, "timeoutMs": 30000});
  await zoomOut();
}, {"emphasis": "케이스의 전제와 단계"});
await padTo(DWELL);
