// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/executions");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 실행\"]");
// ---record---
await subtitleSpan("테스트 실행은 회차별 케이스 판정을 보여줍니다", HOLD[0], async () => {
  await highlight("role=heading[name=\"테스트 실행\"]", {});
}, {"emphasis": "케이스 판정"});
await padTo(DWELL);
