// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/executions");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 실행\"]");
// ---record---
await subtitleSpan("실패한 케이스는 같은 ID로 수행 화면에서 이어집니다", HOLD[0], async () => {
  await zoom("role=button[name=/SCN-LEDGER-001 규정명으로 개정 건 검색 실패/]", {"scale": 1.4});
  await highlight("role=button[name=/SCN-LEDGER-001 규정명으로 개정 건 검색 실패/]", {});
  await zoomOut();
  await click("role=button[name=\"실행 열기\"] >> nth=0");
  await waitFor("role=heading[name=\"테스트 수행\"]", {});
}, {"emphasis": "같은 ID"});
await padTo(DWELL);
