// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/executions/EXE-20260908-0042");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 수행\"]");
// ---record---
await subtitleSpan("수행 화면에는 실행 이력과 수행 대기열이 나란히 있습니다", HOLD[0], async () => {
  await highlight("role=heading[name=\"수행 대기열\"]", {});
}, {"emphasis": "수행 대기열"});
await padTo(DWELL);
