// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/executions/EXE-20260908-0042");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 수행\"]");
// ---record---
await subtitleSpan("단계마다 동의, 오탐, 미탐, 재실행 필요로 검토합니다", HOLD[0], async () => {
  await zoom("role=button[name=/02 SCN-LEDGER-001/]", {"scale": 1.4});
  await highlight("role=button[name=\"동의\"] >> nth=0", {});
  await zoomOut();
}, {"emphasis": "검토"});
await padTo(DWELL);
