// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/executions/EXE-20260908-0042");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 수행\"]");
// ---record---
await subtitleSpan("수행은 모델에 보낸 화면 프레임을 보고 단계를 실행합니다", HOLD[0], null, {"emphasis": "화면 프레임"});
await padTo(DWELL);
