// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/executions/EXE-20260908-0042");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 수행\"]");
// ---record---
await subtitleSpan("단계마다 사유 코드, 실행 경로, 재시도와 관측 횟수를 남깁니다", HOLD[0], async () => {
  await highlight("ol.qsteps >> nth=0", {});
}, {"emphasis": "사유 코드"});
await padTo(DWELL);
