// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/executions/EXE-20260908-0042");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 수행\"]");
// ---record---
await subtitleSpan("단계 증적 열기로 판정 근거를 확인합니다", HOLD[0], async () => {
  await click("role=button[name=\"SCN-LEDGER-001 2단계 증적 열기\"]");
  await waitFor("role=heading[name=\"실패 증적 상세\"]", {});
}, {"emphasis": "판정 근거"});
await padTo(DWELL);
