// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/evidence/EXE-20260908-0042/EVD-0042-SCN-LEDGER-001-2");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"실패 증적 상세\"]");
// ---record---
await subtitleSpan("타임라인에서 실패 시점과 직전 화면을 오갑니다", HOLD[0], async () => {
  await zoom("role=heading[name=\"단계 타임라인\"]", {"scale": 1.3});
  await highlight("role=heading[name=\"단계 타임라인\"]", {});
  await click("role=button[name=/실패 직전/]");
  await click("role=button[name=/실패 시점/]");
  await zoomOut();
}, {"emphasis": "실패 시점"});
await padTo(DWELL);
