// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/evidence/EXE-20260908-0042/EVD-0042-SCN-LEDGER-001-2");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"실패 증적 상세\"]");
// ---record---
await subtitleSpan("판정 근거는 원본이 아니라 모델에 전송된 프레임입니다", HOLD[0], async () => {
  await highlight("role=heading[name=\"판정 근거\"]", {});
}, {"emphasis": "모델에 전송된 프레임"});
await subtitleSpan("모델이 지목한 좌표를 그 프레임 위에 겹쳐 보여줍니다", HOLD[1], null, {"emphasis": "좌표"});
await padTo(DWELL);
