// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/evidence");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 증적\"]");
// ---record---
await subtitleSpan("증적 탭은 실행별로 묶인 증적을 판정으로 거릅니다", HOLD[0], async () => {
  await zoom("role=heading[name=\"저장된 증적\"]", {"scale": 1.3});
  await highlight("role=heading[name=\"저장된 증적\"]", {});
  await zoomOut();
}, {"emphasis": "실행별로"});
await padTo(DWELL);
