// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/evidence");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 증적\"]");
// ---record---
await subtitleSpan("판정, 검토 상태, 사유 코드로 거르고", HOLD[0], async () => {
  await click("role=radio[name=\"실패\"]");
}, {"emphasis": "사유 코드"});
await subtitleSpan("원인 태그와 케이스 ID까지 다섯 축으로 좁힙니다", HOLD[1], null, {"emphasis": "다섯 축"});
await padTo(DWELL);
