// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto('about:blank');
await page.goto(BASE + "/?preview=demo#/evidence");
await page.waitForLoadState('networkidle');
await waitFor("role=heading[name=\"테스트 증적\"]");
// ---record---
await subtitleSpan("목록을 내려 보고 케이스 ID로 좁힙니다", HOLD[0], async () => {
  await scrollTo(".body.pad-lg", {"toRatio": 0.6});
  await typeText("input[placeholder=\"SCN-\"]", "SCN-LEDGER", { secret: false });
}, {"emphasis": "케이스 ID"});
await padTo(DWELL);
