// @generated by dv.py from storyboard.json - remove this line to hand-edit
await page.goto("file:///Users/a11769/Desktop/master-project/demo/scenes/.build/99-outro.html");
await page.waitForLoadState('load');
// ---record---
await page.evaluate(() => document.body.classList.add('play'));
await dwell(3000);
